Create main view controller
sltndevelopments/Tajweed_iOS pull request #7
Opened 2022-03-16 20:30 UTC by halsab

### Что сделано:
- Добавлены и расставлены основные сабвьюхи основного контроллера
- Заменены иконки на png трех масштабов

### Что надо сделать:
- Не обновляет статисткику. Данные в модели не обновляются. Надо продебадиться
- На маленьком экране текст уходит за экран. Надо добавить UIScrollView

2022-03-17 08:22 UTC, ZalyalovIldar requested changes
Чутка подправим 👍🏼

2022-03-17 08:22 UTC, ZalyalovIldar commented on Tajwid/Presentation/Book/ViewController/Main/MainViewModel.swift
> +    var introDesvriptionText =
*introDescriptionText

2022-03-17 08:22 UTC, ZalyalovIldar commented on Tajwid/Presentation/Book/ViewController/Main/MainViewModel.swift
> +    private func obtainBook() {
Чтобы было прозрачнее, лучше вернуть тут книгу и задать полю book результат, типа
```swift 
book = obtaineBook()

2022-03-17 08:22 UTC, ZalyalovIldar commented on Tajwid/Presentation/Book/ViewController/Main/MainViewController.swift
> +        let label = UILabel()
label.translatesAutoresizingMaskIntoConstraints = false ?

2022-03-17 08:22 UTC, ZalyalovIldar commented on Tajwid/Presentation/Book/ViewController/Main/MainViewController.swift
> +        let label = UILabel()
label.translatesAutoresizingMaskIntoConstraints = false ?

2022-03-17 08:22 UTC, ZalyalovIldar commented on Tajwid/Presentation/Book/ViewController/Main/StatisticElementView.swift
> +    required init?(coder: NSCoder) {
Давай сверху добавим еще @available(*, unavailable)

2022-03-17 08:22 UTC, ZalyalovIldar commented on Tajwid/Presentation/Book/ViewController/Main/StatisticElementViewModel.swift
> +    ) {
Тут отступы поехали или это гитхаб шалит? 😄

2022-03-17 08:22 UTC, ZalyalovIldar commented on Tajwid/Service/TabBarBuilders/TabBarControllersBuilder.swift
>          let mainStoryboard = UIStoryboard(name: "Main", bundle: nil)
Это удалить можно)

2022-03-17 09:20 UTC, halsab commented on Tajwid/Presentation/Book/ViewController/Main/MainViewModel.swift
> +    var introDesvriptionText =
👍

2022-03-17 09:21 UTC, halsab commented on Tajwid/Presentation/Book/ViewController/Main/MainViewModel.swift
> +    private func obtainBook() {
ага, ок. тоже сначала так думал. потом решил оставить как есть

2022-09-01 18:43 UTC, ZalyalovIldar approved these changes

2022-09-01 18:43 UTC, ZalyalovIldar commented on Tajwid/Presentation/Book/ViewController/MainViewController/MainViewModel.swift
> +    var introDescriptionText =
**Suggestion 🌟** 
Вынести в Localised strings сразу весь новый текст, а потом перенести остальной

2022-09-01 18:43 UTC, ZalyalovIldar commented on Tajwid/Presentation/Book/ViewController/MainViewController/MainViewModel.swift
> +    var logoImage = UIImage(named: "tajweed_icon")
**Suggestion 🌟** 
Заменить на image literal или вынести в хелперы и доступ через enum или вынести в Image Palette 
(остальные подобные места в текущем ПР прописывать не буду)

2022-09-01 18:43 UTC, ZalyalovIldar commented on Tajwid/Presentation/Book/ViewController/MainViewController/MainViewModel.swift
> +        for (index, module) in book.modules.enumerated() {
Понимаю, что "работает не трожь", но когда нибудь там в будущем может стоит попробовать снизить сложность до O(n) ))

2022-09-01 18:43 UTC, ZalyalovIldar commented on Tajwid/Presentation/Book/ViewController/MainViewController/MainViewModel.swift
> +    private func obtainBook() -> Book {
**Suggestion 🌟** 
Возможно стоит вынести в отдельный класс сервис, который бы возвращал книгу. По ощущениям доступ к ней может пригодится не только из этого класса.

2022-10-15 18:46 UTC, merged